NUMPY LIBRARY: numerical python
IT IS BASICALLY AN ARRAY OF A LIST,IT IS MEMORY EFFICIENT
POWERFULL OPERATIONS
EFFICIENT MATHEMATICAL CALCULATIONS
FASTER THAN LIST
WORKS ON BIGGER DATA,MILLIONS OF DATA ROWS



In [2]:
#CREATION OF ARRAY,no.array()method to convert list into an array
! pip install numpy

we have known the methods
np.array
np.zeros
np.ones
np.eye
np.full

In [10]:
import numpy as np
oned_array=np.array([2,3,4])
print(oned_array)
#2darray
twod_array=np.array([[2,3,4],[5,6,7]])
print(twod_array)
#zeros,need to pass shape in tuple
zeros_array=np.zeros((3,4))
print(zeros_array)
#ones array
ones_array=np.ones((6,7))
print(ones_array)
#full array by your given number
full_array=np.full((2,5),9)
print(full_array)
#identity_matrix:diagnols are ones and rest are 0
identity_matrix=np.eye(3)
print(identity_matrix)


[2 3 4]
[[2 3 4]
 [5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[9 9 9 9 9]
 [9 9 9 9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


NOW TO CHECK THR ARRAY WE HAVE DIFFERENT ATTRIBUTES/PROPERTIES
1)SHAPE.....TELLS AS NUM OF ROWS AND COLUMNS
2)SIZE....HOW MANY ELEMENTS IT CONTAINS
3)ASTYPE......WE CAN CHANGE THE TYPE OF ARRAY ELEMENTS INTO NEW ONE
4)DTYPE.....TYPE OF ELEMENTS IN AN ARRAY,,,,FLOAT,INT,STR
5)NDIM....NUM OF DIMENSIONS.....1D,2D OR 3D ARRAY

In [18]:
import numpy as np
oned_array=np.array([[[2,3,4],[4,5,6]],[[4,5,6],[3,5,6]]])
print(oned_array.shape)
print(oned_array.size)
print(oned_array.astype('float64'))
print(oned_array.dtype)
print(oned_array.ndim)

(2, 2, 3)
12
[[[2. 3. 4.]
  [4. 5. 6.]]

 [[4. 5. 6.]
  [3. 5. 6.]]]
int64
3


arthematic and aggregation on numpy array
ARTHEMATIC MEANS....+,-,*,**,/,//,%
AGGREGATION.....STATISTICAL SUMMARY....MEAN,MAX,MIN,STD,VAR


In [23]:
#arthematic operations
import numpy as np
oned_array=np.array([2,3,4])
print(oned_array+10)
print(oned_array-10)
print(oned_array/10)
print(oned_array*10)
print(oned_array**10)
print(oned_array//10)
print(oned_array%10)


[12 13 14]
[-8 -7 -6]
[0.2 0.3 0.4]
[20 30 40]
[   1024   59049 1048576]
[0 0 0]
[2 3 4]


In [21]:
#aggregation
import numpy as np
oned_array=np.array([2,3,4])
print(oned_array.mean())
print(oned_array.sum())
print(oned_array.min())
print(oned_array.max())
print(oned_array.std())
print(oned_array.var())


3.0
9
2
4
0.816496580927726
0.6666666666666666


INDEXING AND SLICING....FANCY INDEXING,BOOLEAN MASKING
INDEXING MEAN TAKING A SINGLE ELEMENT FROM AN ARRAY USING THEIR LOCATION
SLICING MEAN SUBSET OF ARRAY...IT TAKES 3 ARGUMENTS...START,STOP AND STEP
FANCY INDEXING MEANS USING ARRAY OF INDICES TO ACCESS MULTIPLE ELEMENTS,YOU SELECT MULTIPLE ELEMENTS/INDICES AT ONCE
BOOLEAN MASKING MEANS OF USING CONDITIONS TO ACCESS ELEMENTS

In [ ]:
#INDEXING
import numpy as np
oned_array=np.array([2,3,4,5,6,7,8,9,0,6,4,3,3,2,2,2,2,2,2,2,2,2,2])
print(oned_array[0])
print(oned_array[1])
print(oned_array[2])
#fancy indicing....pass a list of indices..so []for index..another[]for list
print(oned_array[[0,2]])
print(oned_array[[1,2]])
#boolean masking..use of square bracket
print(oned_array[oned_array>3])

2
3
4
[2 4]
[3 4]
[4 5 6 7 8 9 6 4]


In [41]:
#slicing....taking subset of array
import numpy as np
oned_array=np.array([2,3,4,5,6,7,8,9,0,6,4,3,10,20])
print(oned_array[0:6:1])
print(oned_array[:6:1])
print(oned_array[0::2])
print(oned_array[::3])

[2 3 4 5 6 7]
[2 3 4 5 6 7]
[ 2  4  6  8  0  4 10]
[ 2  5  8  6 10]


RESHAPING AND MANIPULATION OF ARRAY
RESHAPE......CHANGE THE DIMENSION OF ARRAY...IF ITS 1D...IT CAN CONVERT IT TO 2D,3D AND SO ON
FLATTEN.....HIGHER DIMENSION ARRAYS TO 1D...IT PROVIDES COPY
RAVEL....IT PROVIDES VIEW..IT PROVIDES A VIEW...MEANS CHANGE REFLACTS IN ORIGINAL ARRAY AS WELL...IT DOESNT PROVIDE COPY....
DIFFERENCE BTWEEN RAVEL AND FLATTEN....
FLATTEN RETUENS COPY...CONVERT INTO 1D
RAVEL RETURNS VIEW...THOUGH BOTH USED FOR 1D ARRAY


In [48]:
#RESHAPING
import numpy as np
oned_array=np.array([2,3,4,5,6,7,8,9,0,6,4,3,23,44,10,20])
print(oned_array.reshape(8,2))
print(oned_array.flatten())
print(oned_array.ravel())

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [ 0  6]
 [ 4  3]
 [23 44]
 [10 20]]
[ 2  3  4  5  6  7  8  9  0  6  4  3 23 44 10 20]
[ 2  3  4  5  6  7  8  9  0  6  4  3 23 44 10 20]


REMOVING OF ARRAY ELEMENT IN AN ARRAY,THERE IS A FUNCTION NAMED AS:
DELETE
IT PROVIDES ANOTHER ARRAY AFTER MODIFICATION UNLIKE LIST IT DOESNT PROVIDE DELETE FUNVTION IN INPLACE ARRAY...
it take 2 arguments in case of 1d.
3 arguments in case of 2d and higher dimensions
np.delete(new_arr.4,axis=0)

In [ ]:
#REMOVING OF AN ELEMENT FROM ANY ARRAY 1D...VIA DELETE FUNCTION
import numpy as np
new_arr=np.array([2,3,4,5,6,7,8,9])
print(np.delete(new_arr,0))
print(np.delete(new_arr,4))

[3 4 5 6 7 8 9]
[2 3 4 5 7 8 9]


In [ ]:
#REMOVING OF AN ARRAY ELEMENT FROM 2D ARRAY
import numpy as np
arr_2d=np.array([[1,2,3,4],[8,9,0,7]])
print(np.delete(arr_2d,2,axis=1))

[[1 2 4]
 [8 9 7]]


stacking.....horizontally....column 
vertically.....row wise

In [60]:
#stacking
import numpy as np
arr_1=np.array([2,3,4,5,6,7,8,9])
arr_2=np.array([10,11,12,13,14,15,16,17])
print(np.vstack((arr_1,arr_2)))
print(np.hstack((arr_1,arr_2)))

[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


SPLITTING OF AN ARRAY IN PARTS
EQUAL.....NP.SPLIT
HORIZONTALL........NP.HSPLIT
VERTICALL.......NP.VSPLIT
hsplit → works fine on 1D arrays (splits like cutting a line horizontally).

vsplit → requires at least 2D (splits along rows).

In [3]:
#SPLITTING OF AN ARRAY
import numpy as np
arr_1=np.array([2,3,4,5,6,7,8,9])
print(np.split(arr_1,2))
#SPLITTING OF AN ARRAY horizontally
print(np.hsplit(arr_1,4))
#SPLITTING OF AN ARRAY vertically
arr_2=np.array([[2,3,4,5],[6,7,8,9]])
print(np.vsplit(arr_2,2))

[array([2, 3, 4, 5]), array([6, 7, 8, 9])]
[array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([[2, 3, 4, 5]]), array([[6, 7, 8, 9]])]


BROADCSTING AND VECTORIZATION
  BROADCASTING MEANS EXPANDING ARRAY TO MEET THE REQUIREMENTS...IT STRETCHES THE ARRAY SO THAT THE VALUES MAY FILL....
shapes must be equal or anyone of the array it must have 1 value.....otherwise do the reshape thing
VACTORIZATION MEANS....ALL OPERATIONS ARE PERFORMED AT ONCE WITH ARRAY....INSTAED OF LOOPING IT
IT IS 100 TIMS FASTER THAN LOOPS

1. Vectorization

👉 Writing code that operates on whole arrays (vectors, matrices) instead of using explicit loops.

It’s about style of coding: using array operations instead of for loops.

Makes code shorter, cleaner, and much faster (because NumPy uses C under the hood).

Broadcasting

👉 The set of rules NumPy uses to make arrays of different shapes work together in operations.

It’s not about avoiding loops — it’s about aligning shapes.

NumPy "stretches" an array with shape 1 in a dimension to match the other array.

In [74]:
#Broadcasting
import numpy as np
arr_1=np.array([2,3,4,5,6])
arr_2=np.array([10])
new_arr=(arr_1+arr_2)**2
print(arr_1+arr_2)
print(new_arr)

[12 13 14 15 16]
[144 169 196 225 256]


In [75]:
import numpy as np
arr_1=np.array([2,3,4,5,6]) #shape (5,)
arr_2=np.array([[10],[2]]) #shape(2,1)
print(arr_1+arr_2)


[[12 13 14 15 16]
 [ 4  5  6  7  8]]


(1,5)
(2,1)
now there is a comparison of 1 vs 2....
 5 vs 1
 2 rows 5 columns
[[12 13 14 15 16]
 [ 4  5  6  7  8]]

 Step 1 — Align shapes

arr_1.shape = (5,) → rewrite as (1,5) (padding on the left).

arr_2.shape = (2,1) (already 2D).
Step 2 — Compare dimensions (right → left)

Last dim: 5 vs 1 → broadcast 1 → 5.

Next dim: 1 vs 2 → broadcast 1 → 2.

👉 Final result shape = (2,5)


NP.INF....-NP.INF.......FOR INFINITY VALUE 
NP.NAN.....TO SEE IF NAN ,,NOT A NUMBER EXIST...
NP.ISNAN()